// Generated by scripts/hero-slice.py — do not edit. Positions are in source pixels.
export const HERO_W = 1143;
export const HERO_H = 724;
export const WORDMARK_BOX = [396, 68, 529, 110];
export const LAYERS = {
  "emblem": [
    190,
    34,
    190,
    192
  ],
  "tagline": [
    426,
    166,
    474,
    36
  ],
  "icon_note": [
    51,
    288,
    98,
    116
  ],
  "icon_calendar": [
    183,
    273,
    81,
    86
  ],
  "icon_bulb_hi": [
    278,
    328,
    76,
    81
  ],
  "icon_bulb_mid": [
    191,
    368,
    73,
    81
  ],
  "icon_people": [
    103,
    411,
    96,
    103
  ],
  "icon_checklist": [
    231,
    436,
    78,
    88
  ],
  "icon_gear": [
    288,
    403,
    68,
    71
  ],
  "mech_pedestal": [
    362,
    488,
    244,
    54
  ],
  "mech_ring_outer": [
    352,
    266,
    256,
    262
  ],
  "mech_ring_inner": [
    398,
    318,
    164,
    164
  ],
  "mech_left": [
    333,
    416,
    55,
    96
  ],
  "mech_right": [
    572,
    392,
    56,
    116
  ],
  "brain": [
    412,
    330,
    132,
    132
  ],
  "card_today": [
    606,
    263,
    214,
    149
  ],
  "card_week": [
    813,
    263,
    214,
    149
  ],
  "card_month": [
    606,
    395,
    214,
    147
  ],
  "card_quarter": [
    813,
    395,
    214,
    147
  ],
  "overnight": [
    450,
    582,
    188,
    40
  ],
  "line_left": [
    286,
    590,
    161,
    20
  ],
  "line_right": [
    656,
    590,
    168,
    20
  ],
  "ai_text": [
    381,
    616,
    333,
    34
  ],
  "star": [
    522,
    639,
    48,
    45
  ],
  "trails": [
    20,
    256,
    390,
    318
  ]
} as const;
export type LayerName = keyof typeof LAYERS;
