// Generated by scripts/hero-logo-slices.py — do not edit.
// Lockup geometry in multiples of the emblem's navy ring radius, measured from the ring centre.
// Place the ring and the wordmark and tagline land exactly where the original lockup has them.
export const LOGO = {
  /** The emblem file is this many ring radii wide, drawn at this offset from the ring centre. */
  emblem: { size: 2.2, dx: -1.1, dy: -1.1 },
  wordmark: { x: -1.7681, y: 1.0256, w: 3.5134, h: 0.8938 },
  tagline: { x: -1.4724, y: 1.9848, w: 2.9633, h: 0.0791 },
} as const;
