// Generated by scripts/hero-logo-slices.py — do not edit.
// Lockup geometry in multiples of the emblem's navy ring radius, measured from the ring centre.
// Place the ring and the wordmark and tagline land exactly where the original lockup has them.
export const LOGO = {
  /** The emblem file is this many ring radii wide, drawn at this offset from the ring centre. */
  emblem: { size: 2.1768, dx: -1.0466, dy: -1.1159 },
  wordmark: { x: -1.8106, y: 1.0113, w: 3.6568, h: 0.8674 },
  tagline: { x: -1.3006, y: 1.9377, w: 2.609, h: 0.0833 },
  /** The spinning copy is clipped to this band; the static copy ends at its inner edge. */
  wheel: { inner: 0.975, outer: 1.3 },
} as const;
