/**
 * Generate the crossword words for a week, once, and write them out as a seed file.
 *
 * Puzzles are produced one time and given to every subscriber, so the words for a date are a fact
 * about that date rather than about an account. Normally the first run of a local date fetches them
 * and writes them to `daily_puzzles`; this script does the same fetch ahead of time so a week can be
 * reviewed — and committed — before anybody's tablet sees it.
 *
 *   pnpm --filter @daymarkable/runner make:puzzles 2026-09-20
 *
 * It writes packages/puzzles/src/seededWeeks.ts and a sample PDF per crossword day. Every grid is
 * built and validated here, so a word list that will not lay out is caught now rather than at
 * midnight.
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";
import Anthropic from "@anthropic-ai/sdk";
import { composeDailyPuzzle } from "@daymarkable/compose";
import { crosswordWords } from "@daymarkable/news";
import { REPO_ROOT, loadConfig } from "@daymarkable/pipeline";
import {
  buildCrossword,
  cluesByDirection,
  isoWeekday,
  minPlaced,
  puzzleFor,
  seedFor,
  specFor,
  validateCrossword,
  type CrosswordWord,
} from "@daymarkable/puzzles";
import { DateTime } from "luxon";

/**
 * loadConfig reads the repo-root .env and hands back the same model the nightly run uses, so a
 * puzzle generated here is generated by whatever would have generated it at midnight. It also
 * exports the repo root, which matters because `pnpm --filter` runs with cwd = apps/runner.
 */
const config = loadConfig();
const ROOT = REPO_ROOT;

async function main(): Promise<void> {
  const start = process.argv[2];
  if (!start || !/^\d{4}-\d{2}-\d{2}$/.test(start)) {
    console.error("usage: make:puzzles YYYY-MM-DD   (the first day of the week to generate)");
    process.exit(1);
  }
  if (!config.anthropicApiKey) {
    console.error("ANTHROPIC_API_KEY is not set in .env; nothing to ask.");
    process.exit(1);
  }
  const client = new Anthropic({ apiKey: config.anthropicApiKey });

  const days = Array.from({ length: 7 }, (_, i) => DateTime.fromISO(start).plus({ days: i }).toISODate()!);
  const generated = new Map<string, CrosswordWord[]>();
  let spend = 0;

  for (const date of days) {
    const choice = puzzleFor(date);
    if (choice.kind !== "crossword") {
      console.log(`${date}  ${choice.kind} — generated from the date, nothing to fetch`);
      continue;
    }
    const spec = specFor(isoWeekday(date));
    process.stdout.write(`${date}  crossword, asking for ${spec.ask} words for a ${spec.target}-answer ${spec.cols}x${spec.rows} grid ... `);
    const result = await crosswordWords(client, { ask: spec.ask, model: config.decodeModel, log: () => {} });
    spend += result.costUsd;
    if (result.error) {
      console.log(`FAILED: ${result.error}`);
      process.exitCode = 1;
      continue;
    }
    const lens = result.words.map((w) => w.answer.length);
    const band = (lo: number, hi: number) => lens.filter((n) => n >= lo && n <= hi).length;
    console.log(`  lengths: 3-5=${band(3, 5)} 6-8=${band(6, 8)} 9-14=${band(9, 14)} 15+=${band(15, 99)}`);
    const cw = buildCrossword(result.words, seedFor(date, "crossword"), spec);
    const check = validateCrossword(cw);
    const floor = minPlaced(spec);
    const ok = check.ok && cw.placed.length >= floor;
    console.log(
      `${result.words.length} words -> ${cw.placed.length}/${spec.target} placed, ` +
        `${check.ok ? "valid" : `INVALID (${check.unclued.length} unclued)`}, $${result.costUsd.toFixed(4)}`,
    );
    if (!ok) {
      console.log(`  rejected: needs ${floor} answers and a clean grid`);
      process.exitCode = 1;
      continue;
    }
    generated.set(date, result.words);

    const { across, down } = cluesByDirection(cw);
    const out = await composeDailyPuzzle({
      date,
      generatedAt: `${date}T00:07:00-04:00`,
      runLabel: "nightly",
      puzzle: {
        kind: "crossword",
        cols: cw.cols,
        rows: cw.rows,
        grid: cw.grid,
        numbers: new Map(cw.placed.map((p) => [`${p.row},${p.col}`, p.number] as const)),
        across: across.map((p) => ({ number: p.number, clue: p.clue, answer: p.answer })),
        down: down.map((p) => ({ number: p.number, clue: p.clue, answer: p.answer })),
      },
    });
    const file = path.join(ROOT, `puzzle-${date}.pdf`);
    await writeFile(file, out.pdf);
    console.log(`  ${out.pageCount} pages -> ${path.basename(file)} (${across.length} across, ${down.length} down)`);
  }

  if (generated.size === 0) {
    console.log("\nNothing generated.");
    return;
  }
  await writeFile(path.join(ROOT, "packages/puzzles/src/seededWeeks.ts"), seedFile(generated), "utf8");
  console.log(`\nWrote packages/puzzles/src/seededWeeks.ts for ${generated.size} day(s). Total $${spend.toFixed(4)}.`);
}

function seedFile(byDate: Map<string, CrosswordWord[]>): string {
  const entries = [...byDate.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([date, words]) => {
      const lines = words.map((w) => `    { answer: ${JSON.stringify(w.answer)}, clue: ${JSON.stringify(w.clue)} },`).join("\n");
      return `  "${date}": [\n${lines}\n  ],`;
    })
    .join("\n");
  return `/**
 * Crossword words for specific dates, generated ahead of time and committed.
 *
 * GENERATED FILE — written by \`pnpm --filter @daymarkable/runner make:puzzles <first-day>\`. Do not
 * edit by hand; regenerate it.
 *
 * A date listed here does not need a model call on the night: the run finds the words, lays them out
 * with the date's seed, and prints. That is what lets a week be reviewed before it reaches anyone's
 * tablet, and it is why the puzzle is identical for every subscriber whether or not the API is
 * reachable that night. A date NOT listed here is fetched from the model by the first run of the day
 * and stored in \`daily_puzzles\`, which has the same effect from then on.
 */
import type { CrosswordWord } from "./crossword.js";

export const SEEDED_CROSSWORDS: Record<string, readonly CrosswordWord[]> = {
${entries}
};

/** The committed words for a date, or null when that date is not seeded. */
export function seededCrossword(localDate: string): readonly CrosswordWord[] | null {
  return SEEDED_CROSSWORDS[localDate] ?? null;
}
`;
}

await main();
