/**
 * A general-knowledge answer pool with clues.
 *
 * Two jobs. It is the fallback when the model does not answer — a night with no crossword is worse
 * than a night with a crossword built from a fixed pool — and it is the basis on which
 * `CROSSWORD_SPECS` was measured, because a grid's capacity depends entirely on the length mix of
 * the words offered to it and measuring against invented words would prove nothing.
 *
 * Weighted short on purpose: short words are what let a grid interlock. Everything here is meant to
 * be solvable by anyone, since one puzzle goes to every subscriber — no clue needs a particular
 * country, profession or generation. Answers are letters only, and no clue contains its own answer
 * (there is a test).
 */
import type { CrosswordWord } from "./crossword.js";

export const GENERAL_KNOWLEDGE: readonly CrosswordWord[] = [
  // ---- 3 to 5 letters: the interlocking stock
  { answer: "ACHE", clue: "Dull, lasting pain" },
  { answer: "ACORN", clue: "An oak, before it gets going" },
  { answer: "ACRE", clue: "Field measure" },
  { answer: "ALLOY", clue: "Two metals, melted together" },
  { answer: "AMBER", clue: "Fossil tree resin, or the middle light" },
  { answer: "ANKLE", clue: "Joint above the foot" },
  { answer: "APRON", clue: "Worn to keep the flour off" },
  { answer: "ARCH", clue: "Curved support over an opening" },
  { answer: "ATLAS", clue: "Book of maps" },
  { answer: "AUNT", clue: "Parent's sister" },
  { answer: "AXLE", clue: "Rod the wheels turn on" },
  { answer: "BADGE", clue: "Pinned-on proof of who you are" },
  { answer: "BASIL", clue: "Herb that goes with tomato" },
  { answer: "BEACH", clue: "Where the sand meets the sea" },
  { answer: "BLADE", clue: "Cutting edge, or a single grass leaf" },
  { answer: "BLOOM", clue: "What a flower does" },
  { answer: "BRASS", clue: "Copper and zinc, and a section of the orchestra" },
  { answer: "BREAD", clue: "Flour, water, yeast, heat" },
  { answer: "BRICK", clue: "Fired clay block" },
  { answer: "BROOK", clue: "Small stream" },
  { answer: "CANOE", clue: "Paddled, not rowed" },
  { answer: "CEDAR", clue: "Fragrant softwood tree" },
  { answer: "CHALK", clue: "Soft white rock, once found on every classroom wall" },
  { answer: "CHEF", clue: "Runs the kitchen" },
  { answer: "CHIME", clue: "What a clock does on the hour" },
  { answer: "CLAY", clue: "Potter's material" },
  { answer: "CLIFF", clue: "Steep rock face" },
  { answer: "CLOCK", clue: "It tells you how late you are" },
  { answer: "CLOUD", clue: "Water, airborne" },
  { answer: "COAST", clue: "Where the land runs out" },
  { answer: "CORAL", clue: "Reef builder" },
  { answer: "CRANE", clue: "Long-necked bird, or a lifting machine" },
  { answer: "CREEK", clue: "Narrow inlet, or a small stream" },
  { answer: "CRUST", clue: "The outside of a loaf, or of the planet" },
  { answer: "DAIRY", clue: "Where the milk is handled" },
  { answer: "DELTA", clue: "Where a river fans out to meet the sea" },
  { answer: "DIARY", clue: "Kept day by day" },
  { answer: "DOZEN", clue: "Twelve of them" },
  { answer: "DRUM", clue: "Hit, not plucked" },
  { answer: "DUNE", clue: "Hill the wind built" },
  { answer: "EAGLE", clue: "Big bird on a lot of flags" },
  { answer: "EBONY", clue: "Very dark hardwood" },
  { answer: "ELBOW", clue: "Hinge in the middle of the arm" },
  { answer: "ELDER", clue: "Older one, or a hedgerow tree" },
  { answer: "EMBER", clue: "What a fire leaves glowing" },
  { answer: "FABLE", clue: "Short story with a moral, usually with animals" },
  { answer: "FERN", clue: "Shade plant with fronds, no flowers" },
  { answer: "FLOUR", clue: "Ground grain" },
  { answer: "FLUTE", clue: "Blown across, not into" },
  { answer: "FOAM", clue: "Bubbles in a mass" },
  { answer: "FROST", clue: "Ice on the grass by morning" },
  { answer: "GLOBE", clue: "The world, on a stand" },
  { answer: "GRAIN", clue: "What the miller grinds, or wood's pattern" },
  { answer: "GRAPE", clue: "Wine starts here" },
  { answer: "GRASS", clue: "Mown on Saturdays" },
  { answer: "GRAVY", clue: "Poured over the roast" },
  { answer: "HARP", clue: "Plucked and very large" },
  { answer: "HAWK", clue: "Sharp-eyed hunter of the air" },
  { answer: "HEDGE", clue: "Living garden wall" },
  { answer: "HINGE", clue: "What a door turns on" },
  { answer: "HONEY", clue: "What the hive is for" },
  { answer: "IRIS", clue: "Coloured ring of the eye, or a tall flower" },
  { answer: "IVORY", clue: "Off-white, like an old piano key" },
  { answer: "JELLY", clue: "It wobbles" },
  { answer: "KETTLE", clue: "It whistles when it boils" },
  { answer: "KNEE", clue: "Joint that hates stairs" },
  { answer: "LADLE", clue: "Big spoon for soup" },
  { answer: "LAKE", clue: "Water with land all round it" },
  { answer: "LEMON", clue: "Sour yellow citrus" },
  { answer: "LINEN", clue: "Cloth from flax" },
  { answer: "LOAF", clue: "Bread, as baked" },
  { answer: "MANGO", clue: "Sweet tropical fruit with a big stone" },
  { answer: "MAPLE", clue: "Its leaf is famous and its sap is sweet" },
  { answer: "MARBLE", clue: "Polished stone, or a glass sphere" },
  { answer: "MEADOW", clue: "Field left to the grass and the flowers" },
  { answer: "MELON", clue: "Big, round, mostly water" },
  { answer: "METAL", clue: "It conducts, and it rings when struck" },
  { answer: "MOSS", clue: "Soft green stuff on damp stone" },
  { answer: "MOTOR", clue: "It turns fuel or current into motion" },
  { answer: "NEEDLE", clue: "Eye at one end, point at the other" },
  { answer: "NOTCH", clue: "Small cut, deliberately made" },
  { answer: "OASIS", clue: "Water in the desert" },
  { answer: "OCEAN", clue: "The biggest kind of water" },
  { answer: "ONION", clue: "It makes you cry in the kitchen" },
  { answer: "ORBIT", clue: "The path a moon takes" },
  { answer: "OTTER", clue: "River swimmer that floats on its back" },
  { answer: "OVEN", clue: "Where the baking happens" },
  { answer: "PASTA", clue: "Boiled, then drained" },
  { answer: "PEACH", clue: "Fuzzy skin, sweet flesh, big stone" },
  { answer: "PEARL", clue: "An oyster made it" },
  { answer: "PEBBLE", clue: "Stone worn smooth by water" },
  { answer: "PIANO", clue: "Eighty-eight keys" },
  { answer: "PLUM", clue: "Purple stone fruit" },
  { answer: "POND", clue: "Small still water" },
  { answer: "QUILT", clue: "Stitched, padded bed cover" },
  { answer: "RADISH", clue: "Small, red, peppery root" },
  { answer: "RIDGE", clue: "The long top of a hill or a roof" },
  { answer: "RIVER", clue: "It runs to the sea" },
  { answer: "ROOST", clue: "Where the birds settle for the night" },
  { answer: "SADDLE", clue: "You sit on it to ride" },
  { answer: "SALT", clue: "From the sea or the mine, and on every table" },
  { answer: "SANDAL", clue: "Summer shoe, mostly straps" },
  { answer: "SHELL", clue: "What the snail carries" },
  { answer: "SHORE", clue: "Land at the water's edge" },
  { answer: "SLATE", clue: "Grey rock that splits into roofing" },
  { answer: "SLEET", clue: "Rain that cannot decide to be snow" },
  { answer: "SMOKE", clue: "It goes up the chimney" },
  { answer: "SPADE", clue: "For digging, and a suit of cards" },
  { answer: "SPICE", clue: "It makes the food interesting" },
  { answer: "SPINE", clue: "Backbone, or the part of a book with the title on" },
  { answer: "SPOON", clue: "For stirring and for soup" },
  { answer: "STEAM", clue: "Water, having given up on being liquid" },
  { answer: "STEEL", clue: "Iron, improved with carbon" },
  { answer: "STONE", clue: "What the wall is made of" },
  { answer: "STORM", clue: "Weather at its worst" },
  { answer: "STOVE", clue: "You cook on top of it" },
  { answer: "SUGAR", clue: "From cane or beet, and in the biscuits" },
  { answer: "TABLE", clue: "Four legs and a flat top" },
  { answer: "THORN", clue: "The rose's defence" },
  { answer: "THUMB", clue: "The useful one, opposable" },
  { answer: "TIDE", clue: "The sea, coming and going twice a day" },
  { answer: "TIMBER", clue: "Wood, once it is for building" },
  { answer: "TOAST", clue: "Bread, browned" },
  { answer: "TOWEL", clue: "You reach for it after the bath" },
  { answer: "TULIP", clue: "Spring bulb, cup-shaped" },
  { answer: "VALLEY", clue: "The low ground between hills" },
  { answer: "VIOLIN", clue: "Four strings and a bow, tucked under the chin" },
  { answer: "WHEAT", clue: "The bread grain" },
  { answer: "WHEEL", clue: "It goes round" },
  { answer: "WILLOW", clue: "Tree that weeps by the water" },
  { answer: "WOOL", clue: "Off the sheep and into the jumper" },
  { answer: "YEAST", clue: "It makes the dough rise" },
  { answer: "ZEBRA", clue: "Striped, and related to the horse" },

  // ---- 6 to 8 letters
  { answer: "ANCHOR", clue: "It keeps the boat where you left it" },
  { answer: "AUTUMN", clue: "When the leaves turn" },
  { answer: "BALCONY", clue: "Standing room outside an upstairs window" },
  { answer: "BAMBOO", clue: "Fast-growing hollow stem, and a panda's dinner" },
  { answer: "BEACON", clue: "A light lit to be seen a long way off" },
  { answer: "BELLOWS", clue: "Pumped to make a fire draw" },
  { answer: "BLANKET", clue: "It goes on top of the sheet" },
  { answer: "BOULDER", clue: "A rock too big to lift" },
  { answer: "BRIDGE", clue: "It gets you over the water" },
  { answer: "BUTTER", clue: "Churned from cream" },
  { answer: "CABBAGE", clue: "Leafy, round, and boiled too long by tradition" },
  { answer: "CANDLE", clue: "Wax and a wick" },
  { answer: "CANYON", clue: "Gorge a river cut" },
  { answer: "CARAVAN", clue: "A home you tow behind you" },
  { answer: "CARPET", clue: "Fitted floor covering" },
  { answer: "CASTLE", clue: "Built to be difficult to get into" },
  { answer: "CELLAR", clue: "Room below the house, good for wine" },
  { answer: "CHIMNEY", clue: "The smoke's way out" },
  { answer: "CINNAMON", clue: "Spice from rolled bark" },
  { answer: "CLIMATE", clue: "Weather, averaged over years" },
  { answer: "COMPASS", clue: "It always knows which way is north" },
  { answer: "COTTAGE", clue: "Small house, usually in the country" },
  { answer: "CRIMSON", clue: "Deep red" },
  { answer: "CRYSTAL", clue: "Solid with its atoms in ranks, and very clear glass" },
  { answer: "CUSHION", clue: "Soft, and it softens the chair" },
  { answer: "CYCLONE", clue: "Storm that turns about its own centre" },
  { answer: "DIAMOND", clue: "Hardest gem, and a baseball field's shape" },
  { answer: "DRAWER", clue: "It slides out of the desk" },
  { answer: "ENGINE", clue: "It does the work in the front of the car" },
  { answer: "FALCON", clue: "Fastest of the hunting birds" },
  { answer: "FEATHER", clue: "A bird is covered in them" },
  { answer: "GARLIC", clue: "Cloves, and a strong opinion about them" },
  { answer: "GLACIER", clue: "A river of ice" },
  { answer: "GRANITE", clue: "Hard speckled rock, good for kitchen tops" },
  { answer: "HAMMER", clue: "It drives the nail" },
  { answer: "HARBOUR", clue: "Sheltered water where boats tie up" },
  { answer: "HARVEST", clue: "Bringing the crop in" },
  { answer: "ISLAND", clue: "Land with water all round" },
  { answer: "JOURNEY", clue: "Getting from here to somewhere else" },
  { answer: "JUNGLE", clue: "Forest that has got out of hand" },
  { answer: "KITCHEN", clue: "Where the cooking is done" },
  { answer: "LANTERN", clue: "A light you carry, with the flame shielded" },
  { answer: "LATTICE", clue: "Crossed strips leaving diamonds of air" },
  { answer: "LAVENDER", clue: "Pale purple, and it smells of the airing cupboard" },
  { answer: "LIBRARY", clue: "Books, lent out" },
  { answer: "MEADOWS", clue: "Grass fields, more than one" },
  { answer: "MERIDIAN", clue: "A line of longitude" },
  { answer: "MINERAL", clue: "Dug up, and not alive" },
  { answer: "MONSOON", clue: "The season the rain arrives with" },
  { answer: "MOUNTAIN", clue: "Big enough that you notice the climb" },
  { answer: "MUSHROOM", clue: "Fungus on the plate" },
  { answer: "OINTMENT", clue: "Rubbed on, not swallowed" },
  { answer: "ORCHARD", clue: "Field of fruit trees" },
  { answer: "OYSTER", clue: "Shellfish that sometimes has a surprise inside" },
  { answer: "PADDOCK", clue: "Small field for a horse" },
  { answer: "PARSLEY", clue: "Green garnish nobody eats" },
  { answer: "PEBBLES", clue: "Small smooth stones, by the shore" },
  { answer: "PELICAN", clue: "Bird with a bag under its beak" },
  { answer: "PENGUIN", clue: "Bird that swims instead" },
  { answer: "PENNANT", clue: "Long tapering flag" },
  { answer: "PEPPER", clue: "It comes with the salt" },
  { answer: "PIGMENT", clue: "What gives paint its colour" },
  { answer: "PILLOW", clue: "Your head goes on it" },
  { answer: "PLATEAU", clue: "High ground that has stopped rising" },
  { answer: "POTTERY", clue: "Fired clay, as a craft" },
  { answer: "PUDDLE", clue: "What the rain leaves on the path" },
  { answer: "PUMPKIN", clue: "Big orange gourd, hollowed out in October" },
  { answer: "RAINBOW", clue: "Sunlight, sorted by water" },
  { answer: "RIBBON", clue: "Tied round the parcel" },
  { answer: "SAFFRON", clue: "The most expensive spice, from a crocus" },
  { answer: "SANDALS", clue: "Open summer shoes" },
  { answer: "SATCHEL", clue: "Shoulder bag for books" },
  { answer: "SAUCER", clue: "The cup stands on it" },
  { answer: "SEAWEED", clue: "It grows in salt water and wraps the sushi" },
  { answer: "SHALLOW", clue: "Not deep" },
  { answer: "SHELTER", clue: "Somewhere out of the weather" },
  { answer: "SILVER", clue: "Second place, and a bright metal" },
  { answer: "SPARROW", clue: "Small brown bird, everywhere" },
  { answer: "SPRING", clue: "Coiled metal, or the season after winter" },
  { answer: "SQUIRREL", clue: "It buries nuts and forgets them" },
  { answer: "STIRRUP", clue: "Your foot rests in it when riding" },
  { answer: "SUMMIT", clue: "The top, and the meeting of leaders" },
  { answer: "SUNRISE", clue: "The start of the light" },
  { answer: "SUNSET", clue: "The end of it" },
  { answer: "THUNDER", clue: "The noise that follows the flash" },
  { answer: "TRELLIS", clue: "Frame the climbing plants go up" },
  { answer: "TROWEL", clue: "Small hand tool for planting or plastering" },
  { answer: "TUNNEL", clue: "A way through rather than over" },
  { answer: "VANILLA", clue: "From an orchid pod, and the plainest ice cream" },
  { answer: "VILLAGE", clue: "Smaller than a town" },
  { answer: "VINEGAR", clue: "Sour, and it goes on the chips" },
  { answer: "WALNUT", clue: "Nut with a wrinkled shell, and a dark wood" },
  { answer: "WEATHER", clue: "What everyone talks about" },
  { answer: "WHISTLE", clue: "Blown to stop the game" },
  { answer: "WINDMILL", clue: "It grinds with the help of the weather" },
  { answer: "WINTER", clue: "The cold one" },

  // ---- 9 to 14 letters
  { answer: "ADVENTURE", clue: "A trip with some risk in it" },
  { answer: "ALLIGATOR", clue: "Broad-snouted reptile of the swamp" },
  { answer: "ARCHITECT", clue: "They draw the building before it exists" },
  { answer: "ASTRONOMY", clue: "The study of what is out there" },
  { answer: "AVALANCHE", clue: "Snow, coming down all at once" },
  { answer: "BLACKBERRY", clue: "Hedgerow fruit picked in late summer" },
  { answer: "BREAKFAST", clue: "The first one of the day" },
  { answer: "BUTTERFLY", clue: "It was a caterpillar" },
  { answer: "CARPENTER", clue: "They work in wood" },
  { answer: "CHOCOLATE", clue: "From a bean, and hard to stop eating" },
  { answer: "CINNAMONS", clue: "Barks used as that warm spice, plural" },
  { answer: "COMPASSES", clue: "More than one needle pointing north" },
  { answer: "CONTINENT", clue: "One of the seven big pieces" },
  { answer: "CROCODILE", clue: "Narrow-snouted reptile of the river" },
  { answer: "DANDELION", clue: "Yellow, then a ball of seeds to blow" },
  { answer: "DAYLIGHT", clue: "What you have between the two ends of the day" },
  { answer: "DOLPHIN", clue: "Clever swimmer that breathes air" },
  { answer: "ELEPHANT", clue: "Biggest thing walking about on land" },
  { answer: "EVERGREEN", clue: "A tree that does not bother with autumn" },
  { answer: "FIREPLACE", clue: "Where the logs go" },
  { answer: "GARDENING", clue: "Weekend work that is never finished" },
  { answer: "GRAPEFRUIT", clue: "Big, bitter breakfast citrus" },
  { answer: "HORIZON", clue: "Where the sea appears to stop" },
  { answer: "INGREDIENT", clue: "One item on the list the recipe needs" },
  { answer: "LANDSCAPE", clue: "The view, as a whole" },
  { answer: "LIGHTHOUSE", clue: "It warns the ships off the rocks" },
  { answer: "MARMALADE", clue: "Preserve made with peel" },
  { answer: "MOUNTAINS", clue: "A whole range of the high ones" },
  { answer: "ORCHESTRA", clue: "Strings, wind, brass and percussion together" },
  { answer: "PINEAPPLE", clue: "Spiky outside, sweet inside, not a pine or an apple" },
  { answer: "RASPBERRY", clue: "Soft red fruit that collapses if you look at it" },
  { answer: "RESERVOIR", clue: "Water kept for later" },
  { answer: "SANDSTONE", clue: "Rock made of stuck-together grains" },
  { answer: "SNOWFLAKE", clue: "Six-sided, and no two the same" },
  { answer: "STRAWBERRY", clue: "Red, with its seeds on the outside" },
  { answer: "SUNFLOWER", clue: "Tall, yellow, and it follows the light" },
  { answer: "TELESCOPE", clue: "It brings the far thing near" },
  { answer: "THERMOMETER", clue: "It settles the argument about the temperature" },
  { answer: "UMBRELLA", clue: "Carried on a doubtful morning" },
  { answer: "VEGETABLE", clue: "The part of dinner you were told to finish" },
  { answer: "WATERFALL", clue: "Where the river gives up on gradual" },
  { answer: "WHEELBARROW", clue: "One wheel, two handles, a load of soil" },
  { answer: "WILDERNESS", clue: "Country nobody has tidied" },
  { answer: "WOODPECKER", clue: "It drums on trees for a living" },
];
