/**
 * Crossword words for specific dates, generated ahead of time and committed.
 *
 * GENERATED FILE — written by `pnpm --filter @daymarkable/runner make:puzzles <first-day>`. Do not
 * edit by hand; regenerate it.
 *
 * A date listed here does not need a model call on the night: the run finds the words, lays them out
 * with the date's seed, and prints. That is what lets a week be reviewed before it reaches anyone's
 * tablet, and it is why the puzzle is identical for every subscriber whether or not the API is
 * reachable that night. A date NOT listed here is fetched from the model by the first run of the day
 * and stored in `daily_puzzles`, which has the same effect from then on.
 */
import type { CrosswordWord } from "./crossword.js";

export const SEEDED_CROSSWORDS: Record<string, readonly CrosswordWord[]> = {
  "2026-09-21": [
    { answer: "ANT", clue: "Insect that lives in colonies" },
    { answer: "BEE", clue: "Honey maker" },
    { answer: "OWL", clue: "Night bird of prey" },
    { answer: "ELM", clue: "Shade tree" },
    { answer: "OAK", clue: "Tree that produces acorns" },
    { answer: "RAIN", clue: "Wet weather" },
    { answer: "SNOW", clue: "Winter precipitation" },
    { answer: "WIND", clue: "Moving air" },
    { answer: "HAIL", clue: "Ice pellets from storms" },
    { answer: "MOSS", clue: "Green growth on rocks" },
    { answer: "FERN", clue: "Leafy shade plant" },
    { answer: "BIRD", clue: "Feathered flyer" },
    { answer: "DEER", clue: "Forest animal with antlers" },
    { answer: "BEAR", clue: "Large wild mammal" },
    { answer: "WOLF", clue: "Pack hunter of the wild" },
    { answer: "FISH", clue: "Gill-breathing animal" },
    { answer: "NEWT", clue: "Small salamander" },
    { answer: "TOAD", clue: "Bumpy-skinned amphibian" },
    { answer: "SWAN", clue: "Graceful water bird" },
    { answer: "SPRING", clue: "Season of renewal" },
    { answer: "SUMMER", clue: "Warmest season" },
    { answer: "AUTUMN", clue: "Fall harvest time" },
    { answer: "WINTER", clue: "Coldest season" },
    { answer: "FROST", clue: "Icy morning crystals" },
    { answer: "THAW", clue: "Melting of ice" },
    { answer: "PETAL", clue: "Part of a flower" },
    { answer: "STAMEN", clue: "Flower's male part" },
    { answer: "THISTLE", clue: "Prickly wild plant" },
    { answer: "NETTLE", clue: "Plant that stings" },
    { answer: "CLOVER", clue: "Four-leaf plant" },
    { answer: "SPIDER", clue: "Eight-legged creature" },
    { answer: "BUTTERFLY", clue: "Colorful winged insect" },
    { answer: "CATERPILLAR", clue: "Butterfly larva" },
    { answer: "BEEHIVE", clue: "Honeybee home" },
    { answer: "ECOSYSTEM", clue: "Community of living things" },
    { answer: "SALT", clue: "Essential seasoning from the sea" },
    { answer: "PEPPER", clue: "Spice that makes you sneeze" },
    { answer: "OIL", clue: "Cooking medium for frying" },
    { answer: "BUTTER", clue: "Dairy spread for toast" },
    { answer: "SUGAR", clue: "Sweet granule for baking" },
    { answer: "FLOUR", clue: "Wheat powder for bread" },
    { answer: "EGG", clue: "Breakfast protein from a hen" },
    { answer: "MILK", clue: "Dairy liquid for cereal" },
    { answer: "BREAD", clue: "Sliced carbs for sandwiches" },
    { answer: "CHEESE", clue: "Dairy product that melts" },
    { answer: "GARLIC", clue: "Pungent bulb for flavor" },
    { answer: "ONION", clue: "Tear-inducing vegetable" },
    { answer: "CARROT", clue: "Orange root vegetable" },
    { answer: "POTATO", clue: "Starchy tuber for fries" },
    { answer: "TOMATO", clue: "Red fruit used as vegetable" },
    { answer: "LETTUCE", clue: "Salad green leafy base" },
    { answer: "APPLE", clue: "Red fruit, teacher's gift" },
    { answer: "BANANA", clue: "Yellow tropical fruit" },
    { answer: "LEMON", clue: "Sour citrus for squeezing" },
    { answer: "COFFEE", clue: "Morning beverage for adults" },
    { answer: "TEA", clue: "Hot drink steeped in leaves" },
    { answer: "WINE", clue: "Fermented grape beverage" },
    { answer: "BEER", clue: "Malty alcoholic drink" },
    { answer: "OVEN", clue: "Appliance for baking" },
    { answer: "STOVE", clue: "Cooktop for heating pans" },
    { answer: "FRIDGE", clue: "Appliance that keeps food cold" },
    { answer: "FREEZER", clue: "Compartment for ice cream" },
    { answer: "SINK", clue: "Basin for washing dishes" },
    { answer: "KNIFE", clue: "Sharp tool for cutting" },
    { answer: "FORK", clue: "Utensil with prongs" },
    { answer: "SPOON", clue: "Utensil for soup" },
    { answer: "PAN", clue: "Cookware for frying" },
    { answer: "POT", clue: "Vessel for boiling water" },
    { answer: "WHISK", clue: "Utensil for beating eggs" },
    { answer: "GRATER", clue: "Tool for shredding cheese" },
  ],
  "2026-09-23": [
    { answer: "RAIN", clue: "Water falling from clouds" },
    { answer: "SNOW", clue: "Winter precipitation" },
    { answer: "WIND", clue: "Moving air" },
    { answer: "HAIL", clue: "Ice pellets from storms" },
    { answer: "FOG", clue: "Thick mist near ground" },
    { answer: "DEW", clue: "Morning moisture on grass" },
    { answer: "FROST", clue: "Ice crystals on cold surfaces" },
    { answer: "STORM", clue: "Violent weather system" },
    { answer: "BREEZE", clue: "Gentle wind" },
    { answer: "GALE", clue: "Strong wind" },
    { answer: "THUNDER", clue: "Sound from a lightning strike" },
    { answer: "RAINBOW", clue: "Spectrum after rain" },
    { answer: "CLOUD", clue: "Water vapor in sky" },
    { answer: "SPRING", clue: "Season of new growth" },
    { answer: "SUMMER", clue: "Warmest season" },
    { answer: "AUTUMN", clue: "Fall season" },
    { answer: "WINTER", clue: "Coldest season" },
    { answer: "TREE", clue: "Woody plant with branches" },
    { answer: "FLOWER", clue: "Colorful plant bloom" },
    { answer: "LEAF", clue: "Flat plant part" },
    { answer: "GRASS", clue: "Green lawn covering" },
    { answer: "MOSS", clue: "Soft green ground plant" },
    { answer: "FERN", clue: "Feathery-leafed plant" },
    { answer: "ROSE", clue: "Thorny flowering plant" },
    { answer: "BIRD", clue: "Feathered animal" },
    { answer: "BEAR", clue: "Large forest mammal" },
    { answer: "DEER", clue: "Graceful horned animal" },
    { answer: "EAGLE", clue: "Large soaring bird" },
    { answer: "WOLF", clue: "Wild canine hunter" },
    { answer: "BUTTERFLY", clue: "Winged insect with colorful wings" },
    { answer: "BEE", clue: "Buzzing pollinator" },
    { answer: "SQUIRREL", clue: "Bushy-tailed tree rodent" },
    { answer: "SALT", clue: "Seasoning mineral" },
    { answer: "PEPPER", clue: "Spicy seasoning" },
    { answer: "FLOUR", clue: "Baking staple" },
    { answer: "SUGAR", clue: "Sweetener" },
    { answer: "OIL", clue: "Cooking liquid" },
    { answer: "YEAST", clue: "Bread rising agent" },
    { answer: "BUTTER", clue: "Dairy spread" },
    { answer: "MILK", clue: "Cow's product" },
    { answer: "EGGS", clue: "Breakfast protein" },
    { answer: "RICE", clue: "Grain staple" },
    { answer: "PASTA", clue: "Italian noodles" },
    { answer: "BREAD", clue: "Sliced loaf" },
    { answer: "CHEESE", clue: "Aged dairy product" },
    { answer: "GARLIC", clue: "Pungent bulb" },
    { answer: "ONION", clue: "Tear-inducing vegetable" },
    { answer: "KNIFE", clue: "Cutting tool" },
    { answer: "OVEN", clue: "Baking appliance" },
    { answer: "STOVE", clue: "Cooking surface" },
    { answer: "SINK", clue: "Washing station" },
    { answer: "FRIDGE", clue: "Cooling appliance" },
    { answer: "FREEZER", clue: "Ultra-cold storage" },
    { answer: "BLENDER", clue: "Mixing appliance" },
    { answer: "WHISK", clue: "Beating utensil" },
    { answer: "LADLE", clue: "Soup-serving spoon" },
    { answer: "GRATER", clue: "Shredding tool" },
    { answer: "BOIL", clue: "Heat to bubbling" },
    { answer: "SAUTE", clue: "Quick-fry method" },
    { answer: "BAKE", clue: "Cook in an oven" },
    { answer: "BREW", clue: "Make coffee or tea" },
    { answer: "COFFEE", clue: "Morning beverage" },
    { answer: "TEA", clue: "Steeped drink" },
    { answer: "VANILLA", clue: "Popular flavoring extract" },
    { answer: "MOUNTAIN", clue: "Everest or K2" },
    { answer: "OCEAN", clue: "Pacific or Atlantic" },
    { answer: "DESERT", clue: "Sahara or Kalahari" },
    { answer: "RIVER", clue: "Nile or Amazon" },
    { answer: "LAKE", clue: "Michigan or Baikal" },
    { answer: "VALLEY", clue: "Low-lying area between hills" },
    { answer: "PLATEAU", clue: "Elevated flat land" },
    { answer: "GLACIER", clue: "Slow-moving river of ice" },
    { answer: "VOLCANO", clue: "Mount Vesuvius, for one" },
    { answer: "ISLAND", clue: "Isolated land surrounded by water" },
    { answer: "ARCHIPELAGO", clue: "Group of islands" },
    { answer: "PENINSULA", clue: "Land jutting into water" },
    { answer: "STRAIT", clue: "Narrow passage between waters" },
    { answer: "BAY", clue: "Body of water partly enclosed by land" },
    { answer: "GULF", clue: "Larger version of a bay" },
    { answer: "CLIFF", clue: "Steep rocky face" },
    { answer: "FOREST", clue: "Large wooded area" },
    { answer: "PRAIRIE", clue: "Flat grassland" },
    { answer: "TUNDRA", clue: "Arctic treeless plain" },
    { answer: "HORIZON", clue: "Where sky meets earth" },
    { answer: "ECLIPSE", clue: "When one celestial body blocks another" },
    { answer: "STAR", clue: "Sun or Sirius" },
    { answer: "COMET", clue: "Icy space object with a tail" },
    { answer: "EQUATOR", clue: "Line dividing Earth into hemispheres" },
    { answer: "POLE", clue: "North or South position" },
    { answer: "TREK", clue: "Long difficult journey" },
    { answer: "VOYAGE", clue: "Extended sea journey" },
  ],
  "2026-09-25": [
    { answer: "ANT", clue: "Tiny insect that works in colonies" },
    { answer: "BEE", clue: "Honey maker that pollinates flowers" },
    { answer: "OWL", clue: "Nocturnal bird of prey" },
    { answer: "ELK", clue: "Large deer of North America" },
    { answer: "FOX", clue: "Cunning red canine" },
    { answer: "RAIN", clue: "Precipitation that falls from clouds" },
    { answer: "SNOW", clue: "Winter precipitation in cold climates" },
    { answer: "HAIL", clue: "Frozen pellets falling from storms" },
    { answer: "DEW", clue: "Morning moisture on grass" },
    { answer: "WIND", clue: "Moving air current" },
    { answer: "FROST", clue: "Frozen coating on plants" },
    { answer: "CLOUD", clue: "Fluffy formation in the sky" },
    { answer: "STORM", clue: "Violent weather system" },
    { answer: "SPRING", clue: "Season of renewal and growth" },
    { answer: "SUMMER", clue: "Warmest season of the year" },
    { answer: "AUTUMN", clue: "Fall season with colorful leaves" },
    { answer: "WINTER", clue: "Coldest season" },
    { answer: "ROSE", clue: "Thorny flowering plant" },
    { answer: "DAISY", clue: "Simple white flower with yellow center" },
    { answer: "TULIP", clue: "Spring bulb flower" },
    { answer: "MOSS", clue: "Small soft plant that grows on rocks" },
    { answer: "FERN", clue: "Plant with feathery fronds" },
    { answer: "CACTUS", clue: "Desert plant with spines" },
    { answer: "BIRCH", clue: "White-barked tree" },
    { answer: "CEDAR", clue: "Fragrant evergreen wood" },
    { answer: "EAGLE", clue: "Majestic bird of prey" },
    { answer: "SALMON", clue: "Fish that swims upstream to spawn" },
    { answer: "BADGER", clue: "Burrowing mammal with striped face" },
    { answer: "BUTTERFLY", clue: "Colorful winged insect" },
    { answer: "FIREFLY", clue: "Glowing beetle of summer nights" },
    { answer: "TORNADO", clue: "Spinning funnel cloud of destruction" },
    { answer: "THUNDER", clue: "Sound that follows lightning" },
    { answer: "AVALANCHE", clue: "Massive snow slide down a mountain" },
    { answer: "SALT", clue: "Mineral flavoring" },
    { answer: "PEPPER", clue: "Spicy seasoning" },
    { answer: "OIL", clue: "Cooking liquid" },
    { answer: "SOY", clue: "Asian sauce ingredient" },
    { answer: "HERB", clue: "Culinary plant" },
    { answer: "SPICE", clue: "Flavor enhancer" },
    { answer: "GARLIC", clue: "Pungent bulb" },
    { answer: "ONION", clue: "Layered vegetable" },
    { answer: "BASIL", clue: "Italian herb" },
    { answer: "THYME", clue: "Garden seasoning" },
    { answer: "TEA", clue: "Hot leaf beverage" },
    { answer: "COFFEE", clue: "Morning brew" },
    { answer: "WINE", clue: "Fermented grapes" },
    { answer: "BEER", clue: "Hoppy beverage" },
    { answer: "MILK", clue: "Dairy liquid" },
    { answer: "CREAM", clue: "Rich dairy product" },
    { answer: "BUTTER", clue: "Dairy spread" },
    { answer: "CHEESE", clue: "Aged dairy product" },
    { answer: "YEAST", clue: "Bread leavening agent" },
    { answer: "FLOUR", clue: "Baking powder base" },
    { answer: "SUGAR", clue: "Sweet granules" },
    { answer: "HONEY", clue: "Bee product sweetener" },
    { answer: "VANILLA", clue: "Flavoring from orchids" },
    { answer: "CINNAMON", clue: "Sweet warming spice" },
    { answer: "KNIFE", clue: "Cutting utensil" },
    { answer: "FORK", clue: "Eating prong tool" },
    { answer: "SPOON", clue: "Stirring utensil" },
    { answer: "PAN", clue: "Cooking vessel" },
    { answer: "POT", clue: "Boiling container" },
    { answer: "OVEN", clue: "Baking appliance" },
    { answer: "STOVE", clue: "Cooking heat source" },
    { answer: "FRIDGE", clue: "Cold food storage" },
    { answer: "SINK", clue: "Washing station" },
    { answer: "MESA", clue: "Flat-topped mountain" },
    { answer: "FJORD", clue: "Narrow inlet of the sea" },
    { answer: "DELTA", clue: "River mouth with branches" },
    { answer: "CANYON", clue: "Deep gorge with steep sides" },
    { answer: "GLACIER", clue: "Slow-moving mass of ice" },
    { answer: "LAGOON", clue: "Shallow coastal body of water" },
    { answer: "PLATEAU", clue: "Elevated flat land" },
    { answer: "VOLCANO", clue: "Mountain that erupts molten rock" },
    { answer: "ISTHMUS", clue: "Narrow strip joining two landmasses" },
    { answer: "ARCHIPELAGO", clue: "Group of islands" },
    { answer: "SKY", clue: "Blue expanse above" },
    { answer: "DUNE", clue: "Sand hill in a desert" },
    { answer: "REEF", clue: "Underwater ridge of rock or coral" },
    { answer: "TIDE", clue: "Ocean's rise and fall" },
    { answer: "GALE", clue: "Strong wind" },
    { answer: "CREST", clue: "Top of a wave or hill" },
    { answer: "RAPIDS", clue: "Fast-flowing river section" },
    { answer: "ESTUARY", clue: "Where river meets tide" },
    { answer: "GULF", clue: "Large bay" },
    { answer: "OASIS", clue: "Desert watering hole" },
    { answer: "MORAINE", clue: "Rock debris left by glacier" },
    { answer: "STRAIT", clue: "Narrow water passage between lands" },
    { answer: "RAVINE", clue: "Deep narrow valley" },
    { answer: "SUMMIT", clue: "Mountain peak" },
    { answer: "SWAMP", clue: "Wetland with trees" },
    { answer: "TERRAIN", clue: "Surface features of land" },
    { answer: "ROUTE", clue: "Path of travel" },
    { answer: "VOYAGE", clue: "Long sea journey" },
    { answer: "ATLAS", clue: "Book of maps" },
    { answer: "EQUATOR", clue: "Imaginary line around Earth's middle" },
    { answer: "AURORA", clue: "Colored sky lights near the poles" },
    { answer: "TEMPEST", clue: "Violent storm at sea" },
    { answer: "AWL", clue: "Pointed tool for making holes" },
    { answer: "SAW", clue: "Cutting tool with a blade" },
    { answer: "NAIL", clue: "Fastener hammered into wood" },
    { answer: "BOLT", clue: "Heavy fastener with a nut" },
    { answer: "LACE", clue: "Decorative fabric or shoe fastener" },
    { answer: "SEAM", clue: "Line where two pieces join" },
    { answer: "KNIT", clue: "Create fabric with needles and yarn" },
    { answer: "DENIM", clue: "Sturdy cotton twill fabric" },
    { answer: "WOOL", clue: "Sheep's fiber for yarn" },
    { answer: "HEMP", clue: "Plant fiber for rope" },
    { answer: "TILE", clue: "Ceramic square for flooring" },
    { answer: "BRICK", clue: "Building block for walls" },
    { answer: "GROUT", clue: "Filler between tiles" },
    { answer: "PLASTER", clue: "Wall coating material" },
    { answer: "MORTAR", clue: "Binding agent for bricks" },
    { answer: "VARNISH", clue: "Glossy wood finish" },
    { answer: "CHISEL", clue: "Tool for cutting wood" },
    { answer: "PLIERS", clue: "Gripping hand tool" },
    { answer: "LATHE", clue: "Machine that spins wood" },
    { answer: "TEMPLATE", clue: "Pattern guide for cutting" },
    { answer: "GAUGE", clue: "Measuring tool for thickness" },
    { answer: "LINT", clue: "Fuzzy fibers from fabric" },
    { answer: "SEWIN", clue: "Stitch with needle and thread" },
    { answer: "TWINE", clue: "Strong twisted string" },
    { answer: "LINEN", clue: "Fabric woven from flax" },
    { answer: "VELVET", clue: "Soft pile fabric" },
    { answer: "SATIN", clue: "Glossy smooth fabric" },
    { answer: "LEATHER", clue: "Tanned animal hide" },
    { answer: "CANVAS", clue: "Heavy fabric for sails" },
    { answer: "OXIDE", clue: "Rust or patina layer" },
    { answer: "GLAZE", clue: "Shiny ceramic coating" },
    { answer: "MOLDING", clue: "Decorative wood trim" },
    { answer: "UPHOLSTER", clue: "Cover furniture with fabric" },
  ],
};

/** The committed words for a date, or null when that date is not seeded. */
export function seededCrossword(localDate: string): readonly CrosswordWord[] | null {
  return SEEDED_CROSSWORDS[localDate] ?? null;
}
